# Use uipcli to package and deploy (for each project.json found) 
name: uipath-pack-deploy

on:
  workflow_call:

jobs:
  GetUipathCLI:
    runs-on: windows-latest
    steps:
    - name: Pack and Deploy
      run: |
            foreach($package in Get-ChildItem -Path ${{ github.workspace }} -Recurse -Filter project.json -File)
                {    
                  # Get some data from the package.json for package naming
                  $json = Get-Content "$package" | Out-String | ConvertFrom-Json
                  $Name = $json.name
                  echo $foo
                  $v= [version] $json.projectVersion
                  $newversion= "{0}.{1}.{2}.{3}" -f $v.Major, $v.Minor, ($v.Build),"${{github.run_number}}"
                  $VERSION=[string]$newversion
                  echo $VERSION
                  echo $Name
                  echo ${{ github.workspace }}\$Name.$VERSION.nupkg
                  # Build and Deploy the Package
                  & "C:\\uipathcli\\lib\\net461\\uipcli.exe" package pack "$package" -o "${{ github.workspace }}" -v $VERSION -l en-US
                  & "C:\\uipathcli\\lib\\net461\\uipcli.exe" package deploy "${{ github.workspace }}\$($Name).$VERSION.nupkg" "https://cloud.uipath.com" "${{secrets.UAT_TENANT_NAME}}" -A ${{secrets.ACCOUNT_NAME}} -I ${{secrets.OAUTH_CLIENT_ID}} -S "${{secrets.OAUTH_CLIENT_SECRET}}" -o "Shared" --applicationScope "${{secrets.OAUTH_CLIENT_SCOPES}}"
                }